#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
memory_defaults.py

Single place for default limits used by the memory skill.
"""

MEMORY_MAX_PER_CATEGORY_DEFAULT = 50
MEMORY_COMPRESSION_THRESHOLD_DEFAULT = 500
MEMORY_ARCHIVE_AFTER_DAYS_DEFAULT = 30

CUE_MAX_KEYWORDS_DEFAULT = 100
CUE_MIN_FREQUENCY_DEFAULT = 2
CUE_DECAY_FACTOR_DEFAULT = 0.95

FORGETTING_HALF_LIFE_DEFAULT = 7
FORGETTING_MIN_STRENGTH_DEFAULT = 0.1

FRAGMENT_MAX_CHARS_DEFAULT = 3000
CONTEXT_PACK_MAX_CHARS_DEFAULT = 1400
POST_WRITE_CONTEXT_MAX_CHARS_DEFAULT = 900

SESSION_SUMMARY_LOOKBACK_HOURS_DEFAULT = 8
SESSION_SUMMARY_MAX_MEMORIES_DEFAULT = 30
SESSION_SUMMARY_MAX_ROWS_DEFAULT = 20

